server:
  port: 4444
spring:
  application:
    name: ribbon-client2
  zipkin:
    base-url: http://sleuth-server
    enabled: true
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/