server:
  port: 8080

spring:
  application:
    name: gateway-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: ribbon-client1_route
        uri: http://ribbon-client1
        predicates:
        - Path= /ribbon-client1/**
      - id: feign-client_route
        uri: lb://my-load-balanced-service
        predicates:
        - Path= /feign-client/**

#路由地址负载均衡，
my-load-balanced-service:
  ribbon:
    listOfServers: localhost:5565,localhost:5575
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule  #负载均衡实现策略类
    NFLoadBalancerRuleClassName: zxl.com.gatewayeureka.loadbanlance.MyLoadBalanceRule  #自定义负载均衡实现策略类
    NFLoadBalancerPingClassName: com.yefengyu.gateway.loadbanlance.HealthExamination  #健康检查配置类，找出不可用的服务，避免调用。如果服务恢复再加到调用列表中。

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8200/eureka,http://peer2:8100/eureka
